
name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Reconfigure git to use HTTP authentication to fix act-cli issues
        run: >
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - run: echo "$GITHUB_CONTEXT"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test:cov

      - name: Post code coverage results to coveralls.io
        uses: coverallsapp/github-action@1.1.3
        if: ${{github.actor != 'nektos/act'}}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create gh-pages branch if it does not exist
        uses: ChristopherDavenport/create-ghpages-ifnotexists@v1
        if: ${{github.actor != 'nektos/act'}}

      - name: Generate docs
        if: ${{github.actor != 'nektos/act' && github.ref == 'refs/heads/dev'}}
        run: |
          npm run docs:clean
          npm run docs

      - name: Publish docs to gh-pages
        if: ${{github.actor != 'nektos/act' && github.ref == 'refs/heads/dev'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
